# quckoo-org/api-tips-workflows/.github/workflows/build-fe.yaml@master
name: CI/CD [* branch]

on:
  workflow_call:
    secrets:
      MATTERMOST_WEBHOOK:
        required: true

jobs:

  notify:
    uses: ./.github/workflows/notify.yaml
    secrets:
      MATTERMOST_WEBHOOK : ${{ secrets.MATTERMOST_WEBHOOK }}