# quckoo-org/api-tips-workflows/.github/workflows/build-be.yaml@master
name: CI/CD [* branch]

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      application:
        type: string
        required: false
      comment:
        type: string
        required: false
      default_chart_version:
        type: string
        required: false
        default: "0.0.0"
    secrets:
      MATTERMOST_WEBHOOK:
        required: true
      HARBOR_ROBOT_TOKEN:
        required: true
      KUBE_CONFIG:
        required: true
      JWT_SECRET_KEY:
        required: true
      SEQ_TOKEN:
        required: true

jobs:
  image_build_and_push:
    uses: ./.github/workflows/build-and-push-image.yaml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      HARBOR_ROBOT_TOKEN : ${{ secrets.HARBOR_ROBOT_TOKEN }}
      JWT_SECRET_KEY : ${{ secrets.JWT_SECRET_KEY }}
      KUBE_CONFIG : ${{ secrets.KUBE_CONFIG }}

  helm_prepare_and_push:
    uses: ./.github/workflows/helm_prepare_and_push.yaml
    needs:
      - image_build_and_push
    with:
      environment: ${{ inputs.environment }}
      short_sha: ${{ needs.image_build_and_push.outputs.short_sha }}
      default_chart_version: ${{ inputs.default_chart_version }}
    secrets:
      HARBOR_ROBOT_TOKEN : ${{ secrets.HARBOR_ROBOT_TOKEN }}

  deploy:
    uses: ./.github/workflows/deploy.yaml
    needs:
      - image_build_and_push
      - helm_prepare_and_push
    with:
      environment: ${{ inputs.environment }}
      short_sha: ${{ needs.image_build_and_push.outputs.short_sha }}
      image_version: ${{ needs.image_build_and_push.outputs.image_version }}
      default_chart_version: ${{ inputs.default_chart_version }}
    secrets:
      KUBE_CONFIG : ${{ secrets.KUBE_CONFIG }}
      HARBOR_ROBOT_TOKEN : ${{ secrets.HARBOR_ROBOT_TOKEN }}
      SEQ_TOKEN : ${{ secrets.SEQ_TOKEN }}

  notify:
    uses: ./.github/workflows/notify.yaml
    needs:
      - deploy
    with:
      environment: ${{ inputs.environment }}
      application: ${{ inputs.application }}
      comment: ${{ inputs.comment }}
    secrets:
      MATTERMOST_WEBHOOK : ${{ secrets.MATTERMOST_WEBHOOK }}
