# quckoo-org/api-tips-workflows/.github/workflows/build-and-push-image.yaml@master
name: 'Build and push docker image'

on:
  workflow_call:
    outputs:
      image_version:
        description: "Image version"
        value: ${{ jobs.image_build_and_push.outputs.image_version }}
      short_sha:
        description: "Short sha"
        value: ${{ jobs.image_build_and_push.outputs.short_sha }}
      postgres_password:
        description: "Postgres password"
        value: ${{ jobs.get_password.outputs.postgres_password }}
      redis_password:
        description: "Redis password"
        value: ${{ jobs.get_password.outputs.redis_password }}
    inputs:
      environment:
        type: string
        required: true
    secrets:
      HARBOR_ROBOT_TOKEN:
        required: true
      JWT_SECRET_KEY:
        required: false
      KUBE_CONFIG:
        required: false

jobs:
  get_password:
    runs-on: self-hosted
    if: ${{ always() && !(contains(needs.*.result, 'failure')) && !cancelled() }}
    outputs:
      postgres_password: ${{ steps.get_postgres_password.outputs.postgres_password }}
      redis_password: ${{ steps.get_postgres_password.outputs.redis_password }}
    container:
      image: ghcr.io/helmfile/helmfile:v1.0.0-rc.7
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get postgres password
      id: get_postgres_password
      run: |
        echo ${{ secrets.KUBE_CONFIG }} | base64 -d > ~/CONFIG
        export KUBECONFIG=~/CONFIG
        postgres_password=$(kubectl get secret "postgresql-bitnami" -o jsonpath="{.data.postgres-password}" | base64 -d)
        echo "::add-mask::$postgres_password"
        echo "postgres_password=$postgres_password" >> $GITHUB_ENV

    - name: Get redis password
      id: get_redis_password
      run: |
        echo ${{ secrets.KUBE_CONFIG }} | base64 -d > ~/CONFIG
        export KUBECONFIG=~/CONFIG
        redis_password=$(kubectl get secret "redis" -o jsonpath="{.data.redis-password}" | base64 -d)
        echo "::add-mask::$redis_password"
        echo "redis_password=$redis_password" >> $GITHUB_ENV

  image_build_and_push:
    runs-on: self-hosted
    if: ${{ always() && !(contains(needs.*.result, 'failure')) && !cancelled() }}
    needs:
      - get_password
    outputs:
      short_sha: ${{ steps.short_sha_step.outputs.sha }}
      image_version: ${{ steps.set_image_version.outputs.image_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to [Harbor]
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.HARBOR_HOST }}
          username: ${{ vars.HARBOR_ROBOT_NAME }}
          password: ${{ secrets.HARBOR_ROBOT_TOKEN }}

      - name: Get short sha
        uses: benjlevesque/short-sha@v2.1
        id: short_sha_step
        with:
          length: 7

      - name: Set [short_sha] in [GITHUB_OUTPUT]
        run: |
          echo "short_sha set up to [${{ steps.short_sha_step.outputs.sha }}]" >> "$GITHUB_STEP_SUMMARY"

      - name: Build and push Docker image [Development version]
        if: ${{ inputs.environment == 'development' && github.ref_type != 'tag' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            "SHA_COMMIT=${{ steps.short_sha_step.outputs.sha }}"
            "BRANCH_NAME=${{ github.ref_name }}"
            "POSTGRES_PASSWORD=${{ needs.get_password.outputs.postgres_password }}"
            "REDIS_PASSWORD=${{ needs.get_password.outputs.redis_password }}"
            "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}"
          push: true
          tags: ${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.APPLICATION_NAME }}:${{ steps.short_sha_step.outputs.sha }}-dev, ${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.APPLICATION_NAME }}:latest-dev

      - name: Build and push Docker image [Production version]
        if: ${{ inputs.environment == 'production' && github.ref_type == 'tag' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            "SHA_COMMIT=${{ steps.short_sha_step.outputs.sha }}"
            "VERSION_TAG=${{ github.ref_name }}"
            "POSTGRES_PASSWORD=${{ needs.get_password.outputs.postgres_password }}"
            "REDIS_PASSWORD=${{ needs.get_password.outputs.redis_password }}"
            "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}"
          push: true
          tags: ${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.APPLICATION_NAME }}:${{ github.ref_name }}, ${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.APPLICATION_NAME }}:latest

      - name: Print image version
        id: set_image_version
        run: |
          if [[ "${{ inputs.environment }}" == "production" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "image_version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "Image [${{ inputs.environment }}] version is [${{ github.ref_name }}]" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "image_version=${{ steps.short_sha_step.outputs.sha }}-dev" >> $GITHUB_OUTPUT
            echo "Image [${{ inputs.environment }}] version is [${{ steps.short_sha_step.outputs.sha }}-dev]" >> "$GITHUB_STEP_SUMMARY"
          fi
