# quckoo-org/api-tips-workflows/.github/workflows/build-fe.yaml@master
name: CI/CD [* branch]

on:
  workflow_call:
    secrets:
      MATTERMOST_WEBHOOK:
        required: true
      HARBOR_ROBOT_TOKEN:
        required: true

jobs:
  image_build_and_push:
    uses: ./.github/workflows/build-and-push-image.yaml
    secrets:
      HARBOR_ROBOT_TOKEN : ${{ secrets.HARBOR_ROBOT_TOKEN }}

  notify:
    uses: ./.github/workflows/notify.yaml
    secrets:
      MATTERMOST_WEBHOOK : ${{ secrets.MATTERMOST_WEBHOOK }}