# quckoo-org/api-tips-workflows/.github/workflows/build-and-push-image.yaml@master
name: 'Get passwords'

on:
  workflow_call:
    outputs:
      postgres_password:
        description: "Postgres password"
        value: ${{ jobs.get_password.outputs.postgres_password }}
      redis_password:
        description: "Redis password"
        value: ${{ jobs.get_password.outputs.redis_password }}
    inputs:
      environment:
        type: string
        required: true
    secrets:
      KUBE_CONFIG:
        required: false

jobs:
  get_password:
    runs-on: self-hosted
    if: ${{ always() && !(contains(needs.*.result, 'failure')) && !cancelled() }}
    outputs:
      postgres_password: ${{ steps.get_postgres_password.outputs.postgres_password }}
      redis_password: ${{ steps.get_redis_password.outputs.redis_password }}
    container:
      image: ghcr.io/helmfile/helmfile:v1.0.0-rc.7
    environment: ${{ inputs.environment }}
    steps:
    - name: Get postgres password
      id: get_postgres_password
      run: |
        echo ${{ secrets.KUBE_CONFIG }} | base64 -d > ~/CONFIG
        export KUBECONFIG=~/CONFIG
        postgres_password=$(kubectl get secret "postgresql-bitnami" -o jsonpath="{.data.postgres-password}" | base64 -d)
        echo "postgres_password=$postgres_password" >> $GITHUB_OUTPUT

    - name: Get redis password
      id: get_redis_password
      run: |
        echo ${{ secrets.KUBE_CONFIG }} | base64 -d > ~/CONFIG
        export KUBECONFIG=~/CONFIG
        redis_password=$(kubectl get secret "redis" -o jsonpath="{.data.redis-password}" | base64 -d)
        echo "redis_password=$redis_password" >> $GITHUB_OUTPUT

    - name: Get redis password
      run: |
        echo "Get passwords - ok" >> "$GITHUB_STEP_SUMMARY"
