# quckoo-org/api-tips-workflows/.github/workflows/helm_prepare_and_push.yaml@master
name: 'Build and push docker image'

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      sha:
        type: string
        required: true
      default_chart_version:
        type: string
        required: true
    secrets:
      HARBOR_ROBOT_TOKEN:
        required: true

env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  helm_prepare_and_push:
      runs-on: 'ubuntu-latest'
      if: ${{ always() && !(contains(needs.*.result, 'failure')) && !cancelled() }}
      container:
        image: ghcr.io/helmfile/helmfile:v1.0.0-rc.7
      environment: ${{ inputs.environment }}
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug outputs
        run: |
          echo "Short SHA: ${{ steps.short_sha_step.outputs.sha }}"

      - name: Lint Helm chart
        run: |
          sed -i "s/version\:.*/version\: ${{ inputs.default_chart_version }}-${{ inputs.sha }}/" .helm/${{ vars.APPLICATION_NAME }}/Chart.yaml
          sed -i "s/appVersion\:.*/appVersion\: ${{ inputs.default_chart_version }}-${{ inputs.sha }}/" .helm/${{ vars.APPLICATION_NAME }}/Chart.yaml
          helm lint ./.helm/${{ vars.APPLICATION_NAME }}

      - name: Push Helm chart
        run: |
          echo "${{ secrets.HARBOR_ROBOT_TOKEN }}" | helm registry login ${{ vars.HARBOR_HOST }} --username '${{ vars.HARBOR_ROBOT_NAME }}' --password-stdin
          helm package ./.helm/${{ vars.APPLICATION_NAME }}
          helm push ${{ vars.APPLICATION_NAME }}-${{ inputs.default_chart_version }}-${{ inputs.sha }}.tgz oci://${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.APPLICATION_NAME }}-chart
          echo "Chart [${{ vars.APPLICATION_NAME }}] pushed as [oci://${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.APPLICATION_NAME }}-chart] version [${{ inputs.default_chart_version }}-${{ inputs.sha }}]" >> "$GITHUB_STEP_SUMMARY"
          rm ${{ vars.APPLICATION_NAME }}-${{ inputs.default_chart_version }}-${{ inputs.sha }}.tgz