# quckoo-org/api-tips-workflows/.github/workflows/notify.yaml@master
name: 'Notify MM'

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      application:
        type: string
        required: false
      comment:
        type: string
        required: false
    secrets:
      MATTERMOST_WEBHOOK:
        required: true

jobs:
  notify:
    runs-on: self-hosted
    if: ${{ always() && !(contains(needs.*.result, 'failure')) && !cancelled() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Send notification to Mattermost
        env:
          MATTERMOST_WEBHOOK: "${{ secrets.MATTERMOST_WEBHOOK }}"
        run: |
          GITHUB_ACTION_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H 'Content-Type: application/json' -d "{
            \"username\": \"${{ vars.MM_BOT_NAME }}\",
            \"icon_url\": \"${{ vars.MM_BOT_IMAGE_LINK }}\",
            \"attachments\": [
              {
                \"color\": \"#32CD32\",
                \"fields\": [
                  {
                    \"short\": true,
                    \"title\": \"Info\",
                    \"value\": \"на стенд [${{ inputs.environment }}] задеплоено приложение [${{ inputs.application }}]\"
                  },
                  {
                    \"short\": true,
                    \"title\": \"Branch\",
                    \"value\": \"${{ github.ref_name }}\"
                  },
                  {
                    \"short\": true,
                    \"title\": \"Comment\",
                    \"value\": \"${{ inputs.comment }}\"
                  },
                  {
                    \"short\": true,
                    \"title\": \"Responsible\",
                    \"value\": \"${{ github.actor }}\"
                  },
                  {
                    \"short\": true,
                    \"title\": \"Workflow URL\",
                    \"value\": \"[View in GitHub Actions]($GITHUB_ACTION_URL)\"
                  }
                ]
              }
            ]
          }" $MATTERMOST_WEBHOOK